version: "3.7"
services:
  gobuild:
    image: golang:1.21-bullseye
    environment:
      - GOOS=darwin
      - GOARCH=amd64
    volumes:
      - .:/code
      - $HOME/.aws:/root/.aws
    command: /bin/bash
    working_dir: /code
